// <auto-generated />
using System;
using EfCoreNpgsqlTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

namespace EfCoreNpgsqlTest.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EfCoreNpgsqlTest.DateTimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<NpgsqlRange<DateTime>>("Valid");

                    b.HasKey("Id");

                    b.ToTable("DateTimeEntities");
                });

            modelBuilder.Entity("EfCoreNpgsqlTest.InstantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<NpgsqlRange<Instant>>("Valid");

                    b.HasKey("Id");

                    b.ToTable("InstantEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
